### PR TITLE
Update branch `master` to support Rolling only

### PR DESCRIPTION
**Pull request by asorbini**
This PR updates branch `master` to make it buildable only with the Rolling release.

The PR removes all "feature flags" from `static_config.hpp`, including `RMW_CONNEXT_RELEASE` and any code meant to support earlier releases.

This PR must be merged before creating the next Galactic release in order to be able to create a maintenance branch from the updated `master`.

The code was changed assuming the following "feature configuration":

| Feature | Value |
|------------|---------|
| RMW_CONNEXT_RELEASE | RMW_CONNEXT_RELEASE_ROLLING |
| RMW_CONNEXT_HAVE_PKG_RMW_DDS_COMMON | 1 |
| RMW_CONNEXT_HAVE_SCOPE_EXIT | 1 |
| RMW_CONNEXT_HAVE_GET_DOMAIN | 1 |
| RMW_CONNEXT_HAVE_OPTIONS | 1 |
| RMW_CONNEXT_HAVE_OPTIONS_PUBSUB | 1 |
| RMW_CONNEXT_HAVE_INCOMPATIBLE_QOS | 1 |
| RMW_CONNEXT_HAVE_INCOMPATIBLE_QOS_EVENT | 1 |
| RMW_CONNEXT_HAVE_LIFESPAN_QOS | 1 |
| RMW_CONNEXT_HAVE_MESSAGE_LOST | 1 |
| RMW_CONNEXT_HAVE_SERVICE_INFO | 1 |
| RMW_CONNEXT_HAVE_LOCALHOST_ONLY | 1 |
| RMW_CONNEXT_HAVE_TAKE_SEQ | 1 |
| RMW_CONNEXT_HAVE_SECURITY | 1 |
| RMW_CONNEXT_HAVE_COMMON_MUTEX | 1 |
| RMW_CONNEXT_HAVE_LOAN_MESSAGE | 1 |
| RMW_CONNEXT_HAVE_MESSAGE_INFO_TS | 1 | 
| RMW_CONNEXT_HAVE_GET_INFO_BY_TOPIC | 1 |
| RMW_CONNEXT_HAVE_QOS_PROFILE_API | 1 |
| RMW_CONNEXT_HAVE_TIME_UTILS | 1 | 

**Note to reviewers:** It would be great to review these changes but they are somewhat trivial. I'm creating this PR mainly to keep track of them for future reference.

### CODE REVIEW

**Comment by asorbini** [comment]
CI jobs to validate the changes:

- ci_linux: [Build Status](https://ci.ros2.org/job/ci_linux/14096/)
- ci_osx: [Build Status](https://ci.ros2.org/job/ci_osx/11788/)
- ci_windows: [Build Status](https://ci.ros2.org/job/ci_windows/14195/)

**Review by clalancette — APPROVED** [review]
I just briefly glanced at it, but what I did look at looks good to me.  I think this is the right direction to go in, thanks!

**Review by wjwwood — APPROVED** [review]
I also only skimmed the code changes, but README lgtm, and the general pattern of changes lgtm.

I'm happy if CI is happy :)

**Comment by asorbini** [comment]
Making sure everything is good after merging:

- ci_linux: [Build Status](https://ci.ros2.org/job/ci_linux/14124/)
- ci_osx: [Build Status](https://ci.ros2.org/job/ci_osx/11812/)
- ci_windows: [Build Status](https://ci.ros2.org/job/ci_windows/14221/)

**Pull request merged**
