### PR TITLE
fix: "Failed to parse type hash" message was overly spammy [ros2-50]

### PR DESCRIPTION
**Pull request by trubio-rti**
Having this message printed with too high of a verbosity level makes it too spammy in normal executions of the RMW, making it hard to work with the log files.

### CODE REVIEW

**Comment by asorbini** [comment]
Full CI:

 - Linux: [Build Status](https://ci.ros2.org/job/ci_linux/21011/)
 - Linux (aarch64): [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/15315/) (stopped because not relevant)
 - Windows: [Build Status](https://ci.ros2.org/job/ci_windows/21692/)

**Review by asorbini — APPROVED** [review]
LGTM with green CI.

**Review by fujitatomoya — APPROVED** [review]

**Comment by sloretz** [comment]
In 🧇 meeting we talked about taking this change and also adding a "log once". The log once call would say there was a type mismatch, and tell users to switch the logging mode to debug to see more info. Looking closer I now see that [this is using an rmw_connext specific logging macro](https://github.com/ros2/rmw_connextdds/blob/rolling/rmw_connextdds_common/include/rmw_connextdds/log.hpp), and there's no log-once equivalent.

@clalancette what do you think about taking this change as-is?

**Comment by trubio-rti** [comment]
The CI jobs have expired, I'm running them again:
* Linux: [Build Status](https://ci.ros2.org/job/ci_linux/21638/)
* Windows: [Build Status](https://ci.ros2.org/job/ci_windows/22355/)

Regarding @sloretz's comment, we can file a task to add the log-once feature but I prefer to keep it out of this PR to avoid feature creeping.

**Comment by trubio-rti** [comment]
* Linux: [Build Status](https://ci.ros2.org/job/ci_linux/21647/)
* Windows: [Build Status](https://ci.ros2.org/job/ci_windows/22365/)

**Comment by asorbini** [comment]
@clalancette We are ready to merge this PR, but we have a couple of questions:

- Are "merge commits" ok or should @trubio-rti rebase the branch? 

- If merge commits are ok, do they need the "Signed-off" tag in the message?

Based on your answers we might have to update (and re-run CI as a formality) before merging. Thank you for your help!

**Comment by clalancette** [comment]
Pulls: ros2/rmw_connextdds#149
Gist: https://gist.githubusercontent.com/clalancette/1c2039635efe8ba930f73d1f3b5dd0cf/raw/c1bec87478370bddfd63538fb5d76d04488bdb5e/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw_connextdds_common
TEST args:  --packages-above rmw_connextdds_common
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14453
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21722/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15997/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1227/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22425/)

**Comment by clalancette** [comment]
> * Are "merge commits" ok or should @trubio-rti rebase the branch?

No, we never use Merge commits in the final commit.  That said, using the "Squash and merge" button in GitHub should always do the right thing, which is what we use everywhere else.

That said, it looks like CI on this change wasn't completely run, so I ran it again.

**Comment by MichaelOrlov** [comment]
@clalancette A friendly ping to follow up

**Comment by trubio-rti** [comment]
CI is ok, as we don't run for ARM or RHEL

**Pull request merged**
