### PR TITLE
Add rmw count clients services impl

### PR DESCRIPTION
**Pull request by leeminju531**
this PR is for service counts using it's name like topic.
Related to https://github.com/ros2/ros2cli/pull/771

Signed-off-by: leeminju531 <dlalswn531@naver.com>

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
lgtm with https://github.com/ros2/rmw/pull/334/files#r1057986256 resolved.

**Comment by fujitatomoya** [comment]
CC: @asorbini

**Comment by methylDragon** [comment]
rmw interface changes have been merged
- https://github.com/ros2/rmw/pull/334

**Review by asorbini — APPROVED** [review]
Changes look good to me. They can be merged once ros2/rmw_implementation#208 is in. Thank you @leeminju531 for your contribution!

**Review by fujitatomoya — APPROVED** [review]

**Comment by clalancette** [comment]
CI for this is in https://github.com/ros2/rmw_implementation/pull/208#issuecomment-1740002045

**Pull request merged**
