### PR TITLE
Support Connext 7+

### PR DESCRIPTION
**Pull request by asorbini**
The current version of rmw_connextdds does not support Connext 7+ because of an internal API change.

This PR wraps the "troubling" call with an `#if` checking macro `RTI_DDS_VERSION_MAJOR`, which is defined by the Connext Pro headers.

I have created a [branch to backport the fix to `humble`](https://github.com/ros2/rmw_connextdds/tree/asorbini/connextdds-7-humble) but I noticed there seems to be a "backporting bot" now, so I'm not sure if I should create a separate PR, or if we can use the bot to automatically backport this one. I think the commit should apply cleanly on top of `humble` too.

### CODE REVIEW

**Comment by clalancette** [comment]
> I have created a [branch to backport the fix to `humble`](https://github.com/ros2/rmw_connextdds/tree/asorbini/connextdds-7-humble) but I noticed there seems to be a "backporting bot" now, so I'm not sure if I should create a separate PR, or if we can use the bot to automatically backport this one. I think the commit should apply cleanly on top of `humble` too.

Yeah, you can just use the bot.  Once this has been approved, CI has been run, and merged, you can ask the bot to backport it for you with a `@Mergifyio backport iron humble`.

**Review by clalancette — APPROVED** [review]
Looks reasonable to me with green CI.

**Comment by clalancette** [comment]
> Should I run macOS too?

No, but you should use https://ci.ros2.org/job/ci_launcher/ to make sure to run CI on our default platforms.

**Comment by asorbini** [comment]
Coming back to this PR, and trying to get it merged. I rebased it on top of `rolling`, running CI:

- Linux: [Build Status](https://ci.ros2.org/job/ci_linux/19548/)
- Windows: [Build Status](https://ci.ros2.org/job/ci_windows/20265/)

**Pull request merged**
